<form action="<?= constructUrl('adminLogin') ?>" method="POST">
    <div class="form-div">
        <div class="form-group">
            <label for="exampleInputEmail1" class="connexion-text">Votre email</label>
            <input type="text" class="form-control" id="exampleInputEmail1" name="email" placeholder="email@boitemail.fr" aria-describedby="emailHelp" value="<?= $email ?>">
        </div>


        <div class="form-group">
            <label for="exampleInputText1" class="connexion-text">Votre pseudo</label>
            <input type="text" class="form-control" id="exampleInputText1" name="pseudo" aria-describedby="PseudoHelp" placeholder="Votre pseudo" value="<?= $pseudo ?>">
        </div>

        <div class="form-group">
            <label for="exampleInputPassword1" class="connexion-text">Votre mot de passe</label>
            <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Votre mot de passe">
        </div>

        <?php if (isset($errors)) : ?>

            <small class="text-errors"><?= $errors ?></small>

        <?php endif ?>

        <button type="submit" class="btn btn-primary" name="submit" value="submit">Se connecter</button>
    </div>

</form>