<!-- //* IF IT'S THE SKILL PAGE // -->


<div id="admin-super-box">
    <?php if (isset($_GET['skill'])) { ?>

        <!-- //* UPDATE SKILLS // -->

        <div id="admin-skill-box">

            <div class="admin-box-update">
                <h2>Modifier une compétence</h2>
                <form action="<?= constructUrl('updateSkillsAndPortfolios', ['skill' => $skill->getId()]); ?>" enctype="multipart/form-data" method="POST">
                    <div class="form-div">

                        <div class="form-group">



                            <input type="hidden" name="<?= $skill->getId() ?>" value="<?= $skill->getId() ?>">
                            <?php if ($skill->getImage()) : ?>
                                <img src="<?= asset('images/' . $skill->getImage()) ?>" class="portfolio-main-img">
                            <?php endif ?>
                            <input type="file" class="form-control" id="imageSkill" name="imageSkill" aria-describedby="emailHelp">

                            <?php if (isset($errors['imageSkill'])) : ?>
                                <small class="text-errors"><?= $errors["imageSkill"] ?></small>
                            <?php endif ?>
                        </div>




                        <div class="form-group">

                            <?php if ($skill->getContent()) : ?>
                                <input type="hidden" name="<?= $skill->getId() ?>" value="<?= $skill->getId() ?>">
                                <h3><?= $skill->getContent(); ?></h3>
                            <?php endif ?>
                            <textarea type="text" class="form-control" id="exampleInputText1" name="contentSkill" aria-describedby="PseudoHelp" placeholder="La compétence" value="<?= $content ?>"></textarea>
                            <?php if (isset($errors['contentSkill'])) : ?>
                                <small class="text-errors"><?= $errors['contentSkill'] ?></small>
                            <?php endif ?>
                        </div>


                        <button type="submit" class="btn btn-primary" name="updateSubmitSkill<?= $skill->getId() ?>" value="submit">Modifier</button>


                        </a>
                    </div>
                </form>

            </div>



        </div>
        <!-- //* IF IT'S THE PORTFOLIO PAGE // -->

    <?php } elseif ($_GET['portfolio']) { ?>

        <!-- //* UPDATE PORTFOLIO // -->

        <div id="admin-portfolio-box">

            <div class="admin-box-update">
                <h2>Modifier un portfolio</h2>
                <form action="<?= constructUrl('updateSkillsAndPortfolios', ['portfolio' => $portfolio->getId()]); ?>" enctype="multipart/form-data" method="POST">
                    <div class="form-div">
                        <div class="form-group">
                            <label for="category">Catégorie :</label>
                            <select name="category" id="category">
                                <?php foreach ($categories as $category) : ?>
                                    <option value="<?= intval($category->getIdCategory()); ?>"><?= htmlspecialchars($category->getName()) ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>

                        <div class="form-group">

                            <?php if ($portfolio->getImage()) : ?>
                                <input type="hidden" name="<?= $portfolio->getId() ?>" value="<?= $portfolio->getId() ?>">
                                <img src="<?= asset('images/' . $portfolio->getImage()) ?>" class="portfolio-main-img">
                                <input type="file" class="form-control" id="imagePortfolio" name="imagePortfolio" aria-describedby="emailHelp">
                            <?php endif ?>
                            <?php if (isset($errors['imagePortfolio'])) : ?>
                                <small class="text-errors"><?= $errors["imagePortfolio"] ?></small>
                            <?php endif ?>
                        </div>




                        <div class="form-group">

                            <?php if ($portfolio->getContent()) : ?>
                                <input type="hidden" name="<?= $portfolio->getId() ?>" value="<?= $portfolio->getId() ?>">
                                <h3 class="content-portfolio"><?= $portfolio->getContent(); ?></h3>
                            <?php endif ?>
                            <textarea type="text" class="form-control" id="exampleInputText1" name="contentPortfolio" aria-describedby="PseudoHelp" placeholder="Le contenu" value="<?= $content ?>"></textarea>
                            <?php if (isset($errors['contentPortfolio'])) : ?>
                                <small class="text-errors"><?= $errors['contentPortfolio'] ?></small>
                            <?php endif ?>
                        </div>


                        <button type="submit" class="btn btn-primary" name="updateSubmitPortfolio<?= $portfolio->getId() ?>" value="submit">Modifier</button>


                        </a>
                    </div>
                </form>

            </div>



        </div>






    <?php } ?>
</div>