<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clément Joulin | Développeur Web Junior</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="<?= asset("css/styles.css") ?>">


</head>

<body>

    <?php if (isset($message)) : ?>

        <p class="flash-message"> <?= $message ?> </p>


    <?php endif ?>

    <header>
        <div id="pre-nav">
            <div class="nav-connexion">
                <?php if (isConnected()) : ?>
                    <a href="<?= constructUrl('/deconnexion'); ?>" target="_blank">
                        <h2>Déconnexion</h2>
                    </a>
                <?php else : ?>
                    <a href="<?= constructUrl('/connexion'); ?>" target="_blank">
                        <h2>Connexion</h2>
                    </a>
                <?php endif ?>
                <a href="<?= constructUrl('/inscription'); ?>" target="_blank">
                    <h2>Inscription</h2>
                </a>
            </div>

        </div>
        <!--NAV BAR VISIBLE-->
        <div id="nav-bar">
            <div class="sauf-menu">
                <h1>BIENVENUE</h1>
                <a href="<?= constructUrl('/'); ?>" target="_blank">
                    <img src="<?= asset("images/Accueil.png") ?>" alt="image de d10" class="d10">
                </a>
                <h1>ADMIN</h1>
            </div>
            <div class="menu">
                <h1 class="menu-titre">ACCUEIL</h1>
            </div>


        </div>



        </div>
        </div>




        <?php include $template . '.phtml'; ?>

</body>

</html>