<article class="comments">

    <div class="portfolio-block">
        <div class="ensemble-portfolio">

            <img src="<?= asset('images/' . $portfolioId->getImage()) ?>" class="portfolio-main-img">
            <div class="ensemble-non-img">
                <p class="portfolio-txt"><?= $portfolioId->getContent() ?></p>
            </div>
        </div>



    </div>





    <?php if (isConnected()) : ?>

        <form action="<?= constructUrl('/comments', ['id' => $idPortfolio]); ?>" method="POST">
            <div class="form-div">

                <div class="form-group">
                    <label for="comment" class="comment-text">Votre commentaire</label>
                    <textarea type="text" class="form-control" id="comment" name="comment" placeholder="Veuillez entrer un commentaire" value="<?= $comment ?>"></textarea>
                </div>
                <?php if (isset($errors['comment'])) : ?>
                    <div class="small">
                        <small class="text-errors"><?= $errors['comment'] ?></small>
                    </div>
                <?php endif ?>

                <button type="submit" class="btn btn-primary" name="submit" value="submit">Publier un commentaire</button>
            </div>
        </form>

    <?php else : ?>
        <p> Veuillez vous connecter pour poster un commentaire </p>
    <?php endif ?>

    <?php foreach ($comments as $comment) : ?>
        <div class="portfolio-txt">
            <h2><?= $comment->getUser()->getPseudo(); ?> le <?= $comment->getFormattedCreatedAt() ?></h2>
            <p><?= $comment->getContent(); ?></p>
        </div>
    <?php endforeach ?>

</article>