<article class="comments">

    <div class="portfolio-block">
        <div class="ensemble-portfolio">

            <img src="<?= asset('images/' . $portfolioId->getImage()) ?>" class="portfolio-main-img">
            <div class="ensemble-non-img">
                <p class="portfolio-txt"><?= $portfolioId->getContent() ?></p>
            </div>
        </div>



    </div>






    <form action="<?= constructUrl('/comments', ['id' => $idPortfolio]); ?>" method="POST">
        <div class="form-div">
            <div class="form-group">
                <label for="pseudo" class="comment-text">Votre pseudo</label>
                <input type="text" class="form-control" id="pseudo" name="pseudo" placeholder="Votre pseudo">
            </div>
            <?php if (isset($errors['pseudo'])) : ?>
                <div class="small">
                    <small class="text-errors"><?= $errors['pseudo'] ?></small>
                </div>
            <?php endif ?>

            <div class="form-group">
                <label for="comment" class="comment-text">Votre commentaire</label>
                <textarea type="text" class="form-control" id="comment" name="comment" placeholder="Veuillez entrer un commentaire"></textarea>
            </div>
            <?php if (isset($errors['comment'])) : ?>
                <div class="small">
                    <small class="text-errors"><?= $errors['comment'] ?></small>
                </div>
            <?php endif ?>

            <button type="submit" class="btn btn-primary" name="submit" value="submit">Publier un commentaire</button>
        </div>
    </form>

</article>