<header>
    <div id="pre-nav">
        <div class="nav-connexion">
            <?php if (isConnected()) : ?>
                <a href="<?= constructUrl('/deconnexion'); ?>" target="_blank">
                    <h2>Déconnexion</h2>
                </a>
            <?php else : ?>
                <a href="<?= constructUrl('/connexion'); ?>" target="_blank">
                    <h2>Connexion</h2>
                </a>
            <?php endif ?>
            <a href="<?= constructUrl('/inscription'); ?>" target="_blank">
                <h2>Inscription</h2>
            </a>
        </div>

    </div>
    <!--NAV BAR VISIBLE-->
    <div id="nav-bar">
        <div class="sauf-menu">
            <h1>BIENVENUE</h1>
            <div id="div-d10">
                <img src="<?= asset("images/Accueil.png") ?>" alt="image de d10" class="d10">
            </div>
            <h1>AVENTURIER·E</h1>
        </div>
        <div class="menu">
            <h1 class="menu-titre">MENU</h1>
            <div class="buttons">
                <img src="<?= asset('images/play.png') ?>" alt="boutton play" class="play">
                <img src="<?= asset('images/pause.png') ?>" alt="boutton pause" class="pause">
            </div>


        </div>
    </div>





    <!--NAV BAR POST CLICK-->
    <div class="nav-bar-postclick">
        <img src="<?= asset("images/Accueil.png") ?>" alt="image de d10" class="d10-caché">



        <div class="profil">
            <a href="#profil-description">
                <img src="<?= asset('images/profil modif.png') ?>" alt="image de profil" class="profil-img">
            </a>
            <a href="#profil-description">
                <h2 class="titres-navbar-postclick">PROFIL</h2>
            </a>

        </div>
        <div class="compétences">
            <a href="#compétences-main">
                <img src="<?= asset('images/compétences modif.png') ?>" alt="image de compétences" class="compétences-img">
            </a>
            <a href="#compétences-main">
                <h2 class="titres-navbar-postclick">COMPETENCES</h2>
            </a>

        </div>
        <div class="portfolio">
            <a href="#portfolio-main">
                <img src=" <?= asset('images/portfolio modif.png') ?>" alt="image de portfolio" class="portfolio-img">
            </a>
            <a href="#portfolio-main">
                <h2 class="titres-navbar-postclick">PORTFOLIO</h2>
            </a>
        </div>
        <div class="projets-futurs">
            <a href="#projets-futurs-main">
                <img src=" <?= asset('images/projets futurs modif.png') ?>" alt="image de forge" class="projets-futurs-img">
            </a>
            <a href="#projets-futurs-main">
                <h2 class="titres-navbar-postclick">PROJETS FUTURS</h2>
            </a>

        </div>
        <div class="contact">
            <a href="#footer">
                <img src=" <?= asset('images/contact modif.png') ?>" alt="image de parchemin" class="contact-img">
            </a>
            <a href="#footer">
                <h2 class="titres-navbar-postclick">Contact</h2>
            </a>


        </div>
    </div>


    <div class="identité">
        <div class="partie-gauche">
            <h1>CLEMENT JOULIN</h1>
            <h2 class="dev-text">DEVELOPPEUR WEB JUNIOR <br> EN RECHERCHE DE STAGE</h2>
        </div>

        <div class="partie-droite">
            <img src="<?= asset('images/avatar 2 pixel art-fococlipping-standard.png') ?>" alt="image de moi pixel art" class="avatar">
        </div>


    </div>

</header>

<!--PROFIL-->
<main>

    <div id="profil-description">
        <div class="profil-gauche">
            <h1>SALUTATIONS</h1>
            <p class="profil-bio">Je me nomme Clément Joulin, 29 ans et passionné par la création sous bien des formes : <br>
                écriture, jeu vidéo ou encore musique. J’apprécie avant tout son partage que cela soit via <br>
                mes propres compositions ou en échangeant, débattant, réfléchissant sur d’autres œuvres <br>
                déjà bien établies ou en cours de développement. <br> <br>

                Issu d’une formation de sciences humaines (psychologie et philosophie), me voilà en reconversion <br>
                développeur web et web mobile. <br> <br>

                Me nourrissant de toutes mes expériences, j’adore exercer mon esprit créatif. <br>
                D’une curiosité inextinguible, j’apprends chaque jour auprès de mes pairs et par moi-même. <br> <br>

                En formation avec Simplon depuis fin octobre, je me découvre une nouvelle passion et vocation: <br>
                celle du développement web. Dans le cadre de cette dernière, je suis actuellement à la recherche d’un <br>
                stage afin de développer mes compétences.
            </p>

            <div class="cv-pdf">
                <a href="./CV.pdf" download="CV.pdf" target="_blank"><img src="<?= asset('images/pdf1.png" alt="image de pdf') ?>" class="pdf"></a>
                <h1 class="cv-text">CV</h1>
            </div>


        </div>


        <div class="profil-droite">
            <div class="jeu-vidéo">
                <img src="<?= asset('images/jeu vidéo modif.png') ?>" alt="image de manette" class="jeu-vidéo-img">
                <div class="sauf-manette">
                    <h2>JEU VIDEO</h2>
                    <p>Joueur invétéré sur différentes consoles mais <br>
                        surtout pc, j’aime découvrir des nouveaux univers et tester <br>
                        d’autres mécaniques de jeux. Ma préférence allant tout de même <br>
                        aux rpg, jeux de cartes et plateformer.</p>
                </div>

            </div>
            <div class="écriture">
                <img src="<?= asset('images/écriture modif.png') ?>" alt="image de crayon" class="écriture-img">
                <div class="sauf-crayon">
                    <h2>ECRITURE</h2>
                    <p> Auteur de deux livres publiés, je ne cesse d’élaborer divers <br>
                        projets : romans, pièce de théâtre, poésie et jeu de rôle <br>
                        (scenarii, création de système et univers). Je travaille <br>
                        actuellement sur le développement de mon univers médiéval <br>
                        fantasy en parallèle du roman et du jeu de rôle dont ils sont <br>tirés.
                    </p>
                </div>

            </div>
            <div class="musique">
                <img src="<?= asset('images/musique modif.png') ?>" alt="image de basse" class="musique-img">
                <div class="sauf-basse">
                    <h2>MUSIQUE</h2>
                    <p> Sur mon temps libre, je joue de la basse et compose divers <br>
                        morceaux que cela soit les paroles ou les parties instruments à <br>
                        corde via des logiciels ou non. Avec un ami, nous avons créé <br>
                        une chaîne youtube où nous postons nos créations.
                    </p>
                </div>

            </div>


        </div>





    </div>

    <!--COMPETENCES-->

    <div id="compétences-main">
        <?php foreach ($skills as $skill) : ?>
            <?php if ($skill->getImage()) : ?>

                <img src='<?= asset("images/" . $skill->getImage()); ?>' class="logo">

            <?php endif; ?>
            <?php if ($skill->getContent()) : ?>
                <h3><?= $skill->getContent(); ?></h3>
            <?php endif; ?>


        <?php endforeach ?>
    </div>


    <!--PORTFOLIO-->

    <article>

        <div id="portfolio-main">
            <h1>PORTFOLIO</h1>

            <div class="portfolio-block">
                <?php foreach ($portfolios as $portfolio) : ?>

                    <div class="ensemble-portfolio">
                        <img src="<?= asset('images/' . $portfolio->getImage()) ?>" class="portfolio-main-img">
                        <div class="ensemble-non-img">
                            <p class="portfolio-txt"><?= $portfolio->getContent() ?></p>
                            <a href="<?= constructUrl('/comments', ['id' => $portfolio->getId()]); ?>" target="_blank">
                                <div class="boutton">
                                    <img src="<?= asset('images/souris modif.png') ?>" alt="image de souris" class="souris">
                                    <p class="portfolio-txt">Cliquez ici pour voir les commentaires</p>
                                </div>

                            </a>
                        </div>
                    </div>


                <?php endforeach ?>
            </div>
        </div>

    </article>

    <!--PROJETS FUTURS-->

    <div id="projets-futurs-main">
        <h1>PROJETS FUTURS</h1>

        <div class="projets-futurs-block">

            <div class="site-web-projet">
                <img src="<?= asset('images/site web.png') ?>" alt="image de site web" class="projet-img">
                <p>Un site web présentant mon univers de fiction et recensant tous ses médias : <br>
                    roman, jeu de rôle, jeu de plateau, jeu de cartes et prochainement jeu vidéo. <br>
                    Vous pouvez pour le moment suivre le développement de l’univers et du jeu <br> de
                    rôle en rejoignant mon discord. </p>
                <a href="https://discord.gg/pdumPFYA" target="_blank">
                    <img src="<?= asset('images/discord.png') ?>" alt="image de discord" class="projet-discord">
                </a>



            </div>

            <div class="jeu-vidéo-projet">
                <img src="<?= asset('images/jeu plateforme.png') ?>" alt="jeu de plateforme" class="projet-img">
                <p>Un jeu vidéo plateformer rpg basé sur mon univers médiéval fantasy où on <br>
                    incarnera le protagoniste de mon roman dans ses plus jeunes années.</p>

            </div>




        </div>


    </div>

    <!--API-->

    <div class="api">
        <p>Vous êtes passé niveau 2 ! Cliquez sur le coffre pour recevoir votre récompense !</p>
        <h1>RPG ITEMS API</h1>
        <img src="<?= asset('images/coffre fermé.png') ?>" alt="image de coffre fermé" class="item coffre-fermé">
        <div class="récompense">
            <img src="<?= asset('images/coffre ouvert.png') ?>" alt="image de coffre ouvert" class="item">
            <h1 class="title-item"></h1>
            <h2 class="type-item"></h2>
            <h2 class="rarity-item"></h2>
            <h2 class="slot-item"></h2>
        </div>


    </div>


</main>


<footer>

    <div id="footer">
        <a href="https://www.linkedin.com/in/cl%C3%A9ment-joulin-291a63160/" target="_blank">
            <img src="<?= asset('images/linkedin.png') ?>" alt="logo linkedin" class="logo-footer">
        </a>
        <a href="https://github.com/Kanzann7" target="_blank">
            <img src="<?= asset('images/github.png') ?>" alt="logo github" class="logo-footer">
        </a>
        <a href="mailto:clemjoulin@hotmail.fr" target="_blank">
            <img src="<?= asset('images/mail.png') ?>" alt="logo mail" class="logo-footer">
        </a>
        <div class="footer-discord">
            <img src="<?= asset('images/discord.png') ?>" alt="logo discord" class="logo-footer">
            <p>Kanzan-acolyte pentacolore#7807</p>
        </div>





    </div>
    <a href="<?= constructUrl('/mentions-legales'); ?>" target="_blank">
        <p class="mentions-text">Mentions légales</p>
    </a>

</footer>



<div class="flèche-statique">
    <a href="#nav-bar"> <img src="<?= asset('images/flèche du haut.png') ?>" alt="image de flèche vers le bas">
    </a>

    <script src="<?= asset("js/app.js") ?>"></script>