<form>
    <div class="form-group">
        <label for="exampleInputEmail1">Votre email</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Veuillez entrer votre email">

    </div>

    <div class="form-group">
        <label for="exampleInputEmail1">Votre pseudo</label>
        <input type="text" class="form-control" id="exampleInputText1" aria-describedby="PseudoHelp" placeholder="Votre pseudp">

    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Votre mot de passe</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Votre mot de passe">
    </div>
    <button type="submit" class="btn btn-primary">Envoyer</button>
</form>