<form action="<?= constructUrl('signup') ?>" method="POST">
    <div class="form-div">
        <div class="form-group">
            <label for="exampleInputEmail1" class="connexion-text">Votre email</label>
            <input type="text" class="form-control" id="exampleInputEmail1" name="email" placeholder="email" aria-describedby="emailHelp" placeholder="Veuillez entrer votre email" value="<?= $email ?>">
        </div>
        <?php if (isset($errors['email'])) : ?>
            <div class="small">
                <small class="text-errors"><?= $errors['email'] ?></small>
            </div>
        <?php endif ?>

        <div class="form-group">
            <label for="exampleInputText1" class="connexion-text">Votre pseudo</label>
            <input type="text" class="form-control" id="exampleInputText1" name="pseudo" placeholder="pseudo" aria-describedby="PseudoHelp" placeholder="Votre pseudo" value="<?= $pseudo ?>">
        </div>
        <?php if (isset($errors['pseudo'])) : ?>
            <div class="small">
                <small class="text-errors"><?= $errors['pseudo'] ?></small>
            </div>
        <?php endif ?>

        <div class="form-group">
            <label for="exampleInputPassword1" class="connexion-text">Votre mot de passe</label>
            <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Votre mot de passe">
        </div>
        <?php if (isset($errors['password'])) : ?>
            <div class="small">
                <small class="text-errors"><?= $errors['password'] ?></small>
            </div>
        <?php endif ?>

        <div class="form-group">
            <label for="exampleInputPassword1" class="connexion-text">Confirmez votre mot de passe</label>
            <input type="password" class="form-control" id="exampleInputPassword1" name="password-confirm" placeholder="Confirmez votre mot de passe">
        </div>
        <?php if (isset($errors['password-confirm'])) : ?>
            <div class="small">
                <small class="text-errors"><?= $errors['password-confirm'] ?></small>
            </div>
        <?php endif ?>

        <button type="submit" class="btn btn-primary" name="submit" value="submit">S'inscrire</button>
    </div>
</form>